# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0002_auto_20180124_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='fans',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='idols',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='open',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
