# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0005_auto_20180124_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='fans',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='idols',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='open',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
