# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0006_auto_20180127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fans',
            name='fans',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='idols',
            name='idols',
            field=models.CharField(max_length=11),
        ),
    ]
