# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0007_auto_20180127_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fans',
            new_name='Fan',
        ),
        migrations.RenameModel(
            old_name='Idols',
            new_name='Subsribe',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='fans',
            new_name='fan',
        ),
        migrations.RenameField(
            model_name='subsribe',
            old_name='idols',
            new_name='idol',
        ),
    ]
