# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0008_auto_20180127_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsribe',
            new_name='Subscribe',
        ),
    ]
