# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0009_auto_20180127_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='time',
        ),
    ]
