# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youcan', '0010_remove_content_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='done',
        ),
        migrations.RemoveField(
            model_name='content',
            name='priority',
        ),
    ]
